import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Mintomics",
  description:
    "Review the Mintomics terms of service, including product usage, service availability, and responsibility for tokenomics output.",
  alternates: {
    canonical: "/terms",
  },
};

import LegalLayout from "@/components/legal/LegalLayout";

const toc = [
  { id: "acceptance", title: "1. Acceptance of Terms" },
  { id: "service", title: "2. Description of Service" },
  { id: "user-responsibilities", title: "3. User Responsibilities" },
  { id: "intellectual-property", title: "4. Intellectual Property" },
  { id: "limitation-of-liability", title: "5. Limitation of Liability" },
  { id: "termination", title: "6. Termination" },
  { id: "governing-law", title: "7. Governing Law" },
];

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Service"
      subtitle="The legal framework governing your use of the Mintomics platform and services."
      lastUpdated="April 29, 2026"
      toc={toc}
    >
      <section id="acceptance" className="mb-12 scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">1. Acceptance of Terms</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            By accessing or using the Mintomics platform (the "Service"), you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
          </p>
          <p>
            We reserve the right to update or change our Terms of Service at any time without prior notice. Your continued use of the Service after we post any modifications to the Terms of Service on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Terms of Service.
          </p>
        </div>
      </section>

      <section id="service" className="mb-12 scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">2. Description of Service</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            Mintomics provides a software-as-a-service (SaaS) platform for tokenomics design, simulation, and validation. The outputs generated by the Service, including allocation tables, vesting schedules, and emission curves, are for decision-support purposes only.
          </p>
          <p>
            <strong>Mintomics does not provide financial, legal, or investment advice.</strong> All generated tokenomics models should be reviewed by qualified legal and technical professionals before implementation.
          </p>
        </div>
      </section>

      <section id="user-responsibilities" className="mb-12 scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">3. User Responsibilities</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            You are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer. You agree to accept responsibility for all activities that occur under your account or password.
          </p>
          <p>
            You agree not to use the Service for any illegal or unauthorized purpose. You must not, in the use of the Service, violate any laws in your jurisdiction.
          </p>
        </div>
      </section>

      <section id="intellectual-property" className="mb-12 scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">4. Intellectual Property</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            The Service and its original content, features, and functionality are and will remain the exclusive property of Mintomics and its licensors. The Service is protected by copyright, trademark, and other laws of both the country and foreign countries.
          </p>
          <p>
            Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Mintomics.
          </p>
        </div>
      </section>

      <section id="limitation-of-liability" className="mb-12 scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">5. Limitation of Liability</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            In no event shall Mintomics, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service.
          </p>
          <p>
            We provide the Service on an "AS IS" and "AS AVAILABLE" basis. Mintomics makes no representations or warranties of any kind, express or implied, as to the operation of their services, or the information, content or materials included therein.
          </p>
        </div>
      </section>

      <section id="termination" className="mb-12 scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">6. Termination</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.
          </p>
          <p>
            All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.
          </p>
        </div>
      </section>

      <section id="governing-law" className="scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">7. Governing Law</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which Mintomics operates, without regard to its conflict of law provisions.
          </p>
          <p>
            Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect.
          </p>
        </div>
      </section>
    </LegalLayout>
  );
}
