import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclaimer | Mintomics",
  description:
    "Mintomics provides decision support only. Review generated tokenomics with legal, compliance, and token engineering experts.",
  alternates: {
    canonical: "/disclaimer",
  },
};

import LegalLayout from "@/components/legal/LegalLayout";

const toc = [
  { id: "no-advice", title: "1. Not Financial Advice" },
  { id: "accuracy", title: "2. Accuracy of Models" },
  { id: "responsibility", title: "3. User Responsibility" },
  { id: "professional-review", title: "4. Professional Review" },
];

export default function DisclaimerPage() {
  return (
    <LegalLayout
      title="Disclaimer"
      subtitle="Important legal notices regarding the nature of the information provided by Mintomics."
      lastUpdated="April 29, 2026"
      toc={toc}
    >
      <section id="no-advice" className="mb-12 scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">1. Not Financial Advice</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            The content on the Mintomics platform, including but not limited to AI-generated tokenomics models, projections, and reports, is provided for informational and decision-support purposes only.
          </p>
          <p>
            <strong>Mintomics does not provide financial, investment, legal, or tax advice.</strong> None of the content on this site should be considered a recommendation to buy, sell, or hold any cryptocurrency or token, or to engage in any specific investment strategy.
          </p>
        </div>
      </section>

      <section id="accuracy" className="mb-12 scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">2. Accuracy of Models</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            While we strive to provide the most accurate and up-to-date simulations and models, the Web3 landscape is highly volatile and rapidly evolving. AI-generated outputs are based on heuristics and patterns that may not apply to your specific project or market conditions.
          </p>
          <p>
            Mintomics makes no representations or warranties about the completeness, reliability, or accuracy of the models generated. Any action you take based on the information found on this platform is strictly at your own risk.
          </p>
        </div>
      </section>

      <section id="responsibility" className="mb-12 scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">3. User Responsibility</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            As a founder or user, you are solely responsible for the tokenomics design of your project. Mintomics is a tool to help you visualize and iterate, but it is not a substitute for professional token engineering or economic modeling.
          </p>
          <p>
            Mintomics will not be liable for any losses or damages in connection with the use of our website or the implementation of token models designed using our tools.
          </p>
        </div>
      </section>

      <section id="professional-review" className="scroll-mt-24">
        <h2 className="text-2xl font-bold text-white mb-6">4. Professional Review</h2>
        <div className="space-y-4 text-gray-400 leading-relaxed">
          <p>
            We strongly recommend that all tokenomics designs generated by Mintomics be reviewed by:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Legal counsel specializing in digital assets and securities law</li>
            <li>Experienced token engineers and economic modelers</li>
            <li>Security auditors for smart contract implementation</li>
          </ul>
        </div>
      </section>
    </LegalLayout>
  );
}
